bdd: #Migration automatique
	$(MAKE) oui
	$(MAKE) doctrine
.PHONY: bdd
	

oui: #Migration automatique
	
   php bin/console doctrine:schema:update --force
.PHONY: oui
	

doctrine: #ça lance les fixtures
	 php bin/console doctrine:fixtures:load
.PHONY: doctrine


addGit: #ça envoie un push tout seul
	git add --all
	git commit -m ""
	git push

updateGit: #ça actualise ta branche actuel avec le main
	git fetch origin main
	git merge origin/main

test-pest: ## Do a test on all file and show you the coverage if there is no failed test
   @echo "Running Pest tests..."
   @OUTPUT=`$(PEST) >test-info.txt 2>&1`; \
   RETVAL=$$?; \
if [ $$RETVAL -eq 0 ]; then \
   echo "Pest tests passed"; \
   echo ''; \
   sed -n '9p' ./coverage_summary.txt ; \
   echo ''; \
   rm ./coverage_summary.txt; \
else \
   echo ''; \
   grep "^  Tests:" test-info.txt ; \
   echo ''; \
   echo "Pest tests failed"; \
   rm test-info.txt ; \
fi
                                                                                             